version: '3.7'
services:
# An pretty and structured backend
  backend:
    build: ./
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: classicmodels
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
    networks:
      - network
  db:
    image: mysql:5.7.22
    restart: always    
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: classicmodels
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/storage/dbdata:/var/lib/mysql
      - ./docker/storage/mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - network
networks:
  network:
    driver: bridge
